baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 7

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # Enable to show reading time in minutes for posts
  showReadingTime = false
  # leave empty to disable, enter display text to enable
  lastModDisplay = "最后修改"

[languages]
  [languages.en]
    title = "Colinx Blog"
    subtitle = "Colin's Blog"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Colinx Blog"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Archive"
        url = "/archive"
      [[languages.en.menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories"
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      
