name: Check and correct img CDN URLs

on:
  push:
    branches: [master]
  # pull_request:
    # branches: [master]

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Find and Replace Release
        uses: jacobtomlinson/gha-find-replace@2.0.0
        with:
          find: "blog-1301127393.cos.ap-shanghai.myqcloud.com"
          replace: "blog-1301127393.file.myqcloud.com"
          include: "**/*.md"


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Change img CDN URL"
          title: "Update imgs' CDN URL"
          labels: "URL"
          base: "master"
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: "update-img-url"
          body: "Some imgs' URL need to be updated."
