name: Check and correct text

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-and-lint-text:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: huacnlee.autocorrect
        uses: huacnlee/autocorrect-action@v2.5.4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: lint text"
          title: "Text lint"
          labels: "Lint"
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: "text-lint"
          body: "Some words and sentences need to be updated."
